import { PolicyPreset } from './types';

export const policyPresets: PolicyPreset[] = [
  {
    id: 'basic',
    name: 'Basic Validation',
    description: 'Essential validation rules for general use. Includes schema validation, TTL checks, and cryptographic verification.',
    category: 'basic',
    policy: {
      id: 'basic-preset',
      name: 'Basic Validation',
      version: '1.0.0',
      description: 'Essential validation rules for general use',
      rules: [
        {
          id: 'rule-1',
          type: 'schema',
          name: 'Schema Validation',
          description: 'Validate manifest against KYA schema',
          enabled: true,
          parameters: {
            schemaVersion: '1.0',
          },
          order: 0,
        },
        {
          id: 'rule-2',
          type: 'ttl',
          name: 'Time-to-Live Check',
          description: 'Ensure manifest is not expired',
          enabled: true,
          parameters: {
            maxAge: 24,
            requireExpiration: true,
          },
          order: 1,
        },
        {
          id: 'rule-3',
          type: 'crypto',
          name: 'Cryptographic Verification',
          description: 'Verify manifest signature',
          enabled: true,
          parameters: {
            requireSignature: true,
            requireVerification: true,
          },
          order: 2,
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'strict',
    name: 'Strict Security',
    description: 'Comprehensive security validation with TEE evidence, region restrictions, and enhanced cryptographic checks.',
    category: 'strict',
    policy: {
      id: 'strict-preset',
      name: 'Strict Security Policy',
      version: '1.0.0',
      description: 'Comprehensive security validation for high-security environments',
      rules: [
        {
          id: 'rule-1',
          type: 'schema',
          name: 'Schema Validation',
          description: 'Strict schema validation',
          enabled: true,
          parameters: {},
          order: 0,
        },
        {
          id: 'rule-2',
          type: 'ttl',
          name: 'Time-to-Live Check',
          description: 'Strict TTL requirements',
          enabled: true,
          parameters: {
            maxAge: 12,
            requireExpiration: true,
          },
          order: 1,
        },
        {
          id: 'rule-3',
          type: 'crypto',
          name: 'Cryptographic Verification',
          description: 'Enhanced cryptographic verification',
          enabled: true,
          parameters: {
            requireSignature: true,
            allowedAlgorithms: ['Ed25519', 'Secp256k1'],
            requireVerification: true,
          },
          order: 2,
        },
        {
          id: 'rule-4',
          type: 'tee',
          name: 'TEE Evidence',
          description: 'Require TEE attestation',
          enabled: true,
          parameters: {
            requireTEE: true,
            requireAttestation: true,
            allowedProviders: ['Intel', 'AMD'],
          },
          order: 3,
        },
        {
          id: 'rule-5',
          type: 'region',
          name: 'Geographic Restrictions',
          description: 'Restrict to specific regions',
          enabled: true,
          parameters: {
            permittedRegions: ['US', 'EU', 'CA'],
            forbiddenRegions: ['CN', 'RU'],
          },
          order: 4,
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'financial',
    name: 'Financial Services',
    description: 'Validation policies tailored for financial applications with transaction limits and solvency checks.',
    category: 'financial',
    policy: {
      id: 'financial-preset',
      name: 'Financial Services Policy',
      version: '1.0.0',
      description: 'Financial-grade validation with transaction controls',
      rules: [
        {
          id: 'rule-1',
          type: 'schema',
          name: 'Schema Validation',
          description: 'Financial schema validation',
          enabled: true,
          parameters: {},
          order: 0,
        },
        {
          id: 'rule-2',
          type: 'crypto',
          name: 'Cryptographic Verification',
          description: 'Strong cryptographic requirements',
          enabled: true,
          parameters: {
            requireSignature: true,
            allowedAlgorithms: ['Secp256k1'],
            requireVerification: true,
          },
          order: 1,
        },
        {
          id: 'rule-3',
          type: 'solvency',
          name: 'Solvency Check',
          description: 'Verify agent solvency',
          enabled: true,
          parameters: {
            requireSolvency: true,
            minBalance: 1000,
            chain: 'ethereum',
            provider: 'alchemy',
          },
          order: 2,
        },
        {
          id: 'rule-4',
          type: 'transaction_value',
          name: 'Transaction Limits',
          description: 'Limit transaction values',
          enabled: true,
          parameters: {
            maxValue: 10000,
            minValue: 0.01,
            currency: 'USD',
          },
          order: 3,
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Enterprise-grade validation with comprehensive rule sets, compliance checks, and audit requirements.',
    category: 'enterprise',
    policy: {
      id: 'enterprise-preset',
      name: 'Enterprise Policy',
      version: '1.0.0',
      description: 'Enterprise-grade validation for production systems',
      rules: [
        {
          id: 'rule-1',
          type: 'schema',
          name: 'Schema Validation',
          description: 'Enterprise schema validation',
          enabled: true,
          parameters: {},
          order: 0,
        },
        {
          id: 'rule-2',
          type: 'ttl',
          name: 'Time-to-Live Check',
          description: 'Enterprise TTL requirements',
          enabled: true,
          parameters: {
            maxAge: 8,
            requireExpiration: true,
          },
          order: 1,
        },
        {
          id: 'rule-3',
          type: 'crypto',
          name: 'Cryptographic Verification',
          description: 'Enterprise cryptographic standards',
          enabled: true,
          parameters: {
            requireSignature: true,
            allowedAlgorithms: ['Ed25519', 'Secp256k1'],
            requireVerification: true,
          },
          order: 2,
        },
        {
          id: 'rule-4',
          type: 'tee',
          name: 'TEE Evidence',
          description: 'Require TEE attestation',
          enabled: true,
          parameters: {
            requireTEE: true,
            requireAttestation: true,
            allowedProviders: ['Intel', 'AMD', 'AWS'],
          },
          order: 3,
        },
        {
          id: 'rule-5',
          type: 'solvency',
          name: 'Solvency Check',
          description: 'Enterprise solvency requirements',
          enabled: true,
          parameters: {
            requireSolvency: true,
            minBalance: 5000,
            chain: 'ethereum',
            provider: 'infura',
          },
          order: 4,
        },
        {
          id: 'rule-6',
          type: 'region',
          name: 'Geographic Restrictions',
          description: 'Enterprise region policy',
          enabled: true,
          parameters: {
            permittedRegions: ['US', 'EU', 'APAC'],
          },
          order: 5,
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'development',
    name: 'Development',
    description: 'Relaxed validation rules for development and testing environments.',
    category: 'development',
    policy: {
      id: 'dev-preset',
      name: 'Development Policy',
      version: '1.0.0',
      description: 'Relaxed validation for development',
      rules: [
        {
          id: 'rule-1',
          type: 'schema',
          name: 'Schema Validation',
          description: 'Basic schema validation',
          enabled: true,
          parameters: {},
          order: 0,
        },
        {
          id: 'rule-2',
          type: 'crypto',
          name: 'Cryptographic Verification',
          description: 'Basic signature check',
          enabled: true,
          parameters: {
            requireSignature: false,
          },
          order: 1,
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
];
